### ISSUE TITLE
tampilan menu utama

### ISSUE THREAD

**Issue by anaroyani** [drosanda/apptanya#15]
- buat background latar dengan gambar barang
- desain icon home
- desain icon cari
- desain icon tanya
- desain icon profil
- desain icon lonceng(pemberitahuan)

**Comment by drosanda** [comment]
Tampilan halaman utama sudah diimplementasikan, tinggal dicoba apakah masih ada yang kurang

**Comment by drosanda** [comment]
Done with latest commit
