### ISSUE TITLE
bikin desain halaman pertanyaan

### ISSUE THREAD

**Issue by ruliwidura1** [drosanda/apptanya#16]
Halaman pertanyaan

**Comment by rezziqbal06** [comment]
liat we inspirasinya di www.dribbble.com dengan kata kunci "search" atau "question" @anaroyani

**Comment by anaroyani** [comment]
a nanti teh dibuat langsung desain buat halaman pertanyaan?

**Comment by drosanda** [comment]
Done with latest commit
