### ISSUE TITLE
Tampilan icon

### ISSUE THREAD

**Issue by sintianirahayu** [drosanda/apptanya#19]
tampilan icon untuk aplikasi dan searchbar

**Comment by rezziqbal06** [comment]
icon dapat dicari di feathericon.com atau google icon. jadi gausah bikin dari nol

**Comment by drosanda** [comment]
icon sudah selesai diimplementasikan, consider to close this issue @rezziqbal06 or @anaroyani

**Comment by drosanda** [comment]
Done with latest commit
