### ISSUE TITLE
Membuat Tampilan Home Page

### ISSUE THREAD

**Issue by tiasmra** [drosanda/apptanya#20]
**Is documentation has a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when read documentation on section [...]

**Is the issue related to file(s)? Answer if exists**
This documentation should cover on this file [app/view/amp/page/...].

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by drosanda** [comment]
Tampilan homepage sudah ada di http://apptanya.thecloudalert.com tolong di cek @tiasmra

**Comment by tiasmra** [comment]
Barusan di cek udah bagus a

Pada tanggal Sen, 14 Jun 2021 09.12, Daeng Rosanda ***@***.***>
menulis:

**Comment by drosanda** [comment]
Done with latest commit
