### ISSUE TITLE
buat flowchart

### ISSUE THREAD

**Issue by anaroyani** [drosanda/apptanya#24]
untuk memudahkan sistem proses kerja aplikasi

**Comment by drosanda** [comment]
Flow chart Bertanya Implemented & Verified & Tested
Flow chart Menjawab Implemented & Verified & Tested
Flow chart Profile Implemented & Verified & Tested
Flow chart Notifikasi Implemented & Verified & Tested

Gambar sudah diupdate di ISSUE #25

**Comment by drosanda** [comment]
Done with latest commit
