### ISSUE TITLE
Documentation Issue : Cakupan Pertanyaan

### ISSUE THREAD

**Issue by rezziqbal06** [drosanda/apptanya#9]
**cakupan pertanyaannya mau global atau spesifik?.**
Jadi aplikasi pertanyaan ini tuh mau difokuskan pada pertanyaan seputar apa?

**Comment by anaroyani** [comment]
spesifik aja a, pertanyaan yang mencakup barang

**Comment by rezziqbal06** [comment]
nah pertanyaannya mau 5W 1H atau salah satu dari itu?

**Comment by sintianirahayu** [comment]
mau pake 5W 1H biar lebih mudah a

**Comment by rezziqbal06** [comment]
Kalo gitu, aplikasinya terlalu luas, seperti buat Google. kalo bisa yg spesifikasi aja. Misal pertanyaannya tentang "dimana beli?" atau "gimana buat?" udah gitu aja.

**Comment by sintianirahayu** [comment]
yang "dimana" aja a

**Comment by drosanda** [comment]
Done with latest commit
